/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    places: Place;
    events: Event;
    persons: Person;
    businesses: Business;
    'job-ads': JobAd;
    'traffic-disruptions': TrafficDisruption;
    polls: Poll;
    'check-ins': CheckIn;
    neighborhoods: Neighborhood;
    connections: Connection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    persons: PersonsSelect<false> | PersonsSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    'job-ads': JobAdsSelect<false> | JobAdsSelect<true>;
    'traffic-disruptions': TrafficDisruptionsSelect<false> | TrafficDisruptionsSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    'check-ins': CheckInsSelect<false> | CheckInsSelect<true>;
    neighborhoods: NeighborhoodsSelect<false> | NeighborhoodsSelect<true>;
    connections: ConnectionsSelect<false> | ConnectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  name: string;
  venueName?: string | null;
  address?: string | null;
  neighborhood?: string | null;
  sector?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  place: number | Place;
  startDate: string;
  endDate?: string | null;
  isFree?: boolean | null;
  category?: string | null;
  neighborhoodTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  imageUrl?: string | null;
  sourceUrl?: string | null;
  source?: ('manual' | 'b365' | 'meetup' | 'eventbrite' | 'iabilet' | 'other') | null;
  unverified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: number;
  displayName: string;
  neighborhood?: string | null;
  commuteType?: ('metro' | 'bus' | 'tram' | 'trolley' | 'other') | null;
  commuteRoute?: string | null;
  interests?:
    | {
        interest?: string | null;
        id?: string | null;
      }[]
    | null;
  intent?: ('newcomer' | 'jobseeker' | 'hiring' | 'meeting' | 'curious') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  category?: string | null;
  place?: (number | null) | Place;
  description?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-ads".
 */
export interface JobAd {
  id: number;
  title: string;
  company?: string | null;
  business?: (number | null) | Business;
  place?: (number | null) | Place;
  category?: string | null;
  jobType?: ('full-time' | 'part-time' | 'internship' | 'freelance') | null;
  location?: string | null;
  applyLink?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "traffic-disruptions".
 */
export interface TrafficDisruption {
  id: number;
  reason: string;
  routeType?: ('metro' | 'bus' | 'tram' | 'trolley' | 'street') | null;
  route?: string | null;
  street?: string | null;
  sector?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  source?: string | null;
  sourceUrl?: string | null;
  unverified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: number;
  question: string;
  description?: string | null;
  place?: (number | null) | Place;
  communityType?: ('neighborhood' | 'sector' | 'city') | null;
  communityName?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  options?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-ins".
 */
export interface CheckIn {
  id: number;
  person?: (number | null) | Person;
  event?: (number | null) | Event;
  place?: (number | null) | Place;
  checkedInAt?: string | null;
  openToChat?: boolean | null;
  optIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods".
 */
export interface Neighborhood {
  id: number;
  name: string;
  sector?: string | null;
  description?: string | null;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  type:
    | 'event_place'
    | 'person_event'
    | 'person_neighborhood'
    | 'job_place'
    | 'traffic_event'
    | 'poll_place'
    | 'business_place'
    | 'other';
  sourceType:
    'events' | 'persons' | 'places' | 'job-ads' | 'traffic-disruptions' | 'polls' | 'businesses' | 'neighborhoods';
  source:
    | {
        relationTo: 'events';
        value: number | Event;
      }
    | {
        relationTo: 'places';
        value: number | Place;
      }
    | {
        relationTo: 'persons';
        value: number | Person;
      }
    | {
        relationTo: 'businesses';
        value: number | Business;
      }
    | {
        relationTo: 'job-ads';
        value: number | JobAd;
      }
    | {
        relationTo: 'traffic-disruptions';
        value: number | TrafficDisruption;
      }
    | {
        relationTo: 'polls';
        value: number | Poll;
      }
    | {
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      };
  targetType:
    'events' | 'persons' | 'places' | 'job-ads' | 'traffic-disruptions' | 'polls' | 'businesses' | 'neighborhoods';
  target:
    | {
        relationTo: 'events';
        value: number | Event;
      }
    | {
        relationTo: 'places';
        value: number | Place;
      }
    | {
        relationTo: 'persons';
        value: number | Person;
      }
    | {
        relationTo: 'businesses';
        value: number | Business;
      }
    | {
        relationTo: 'job-ads';
        value: number | JobAd;
      }
    | {
        relationTo: 'traffic-disruptions';
        value: number | TrafficDisruption;
      }
    | {
        relationTo: 'polls';
        value: number | Poll;
      }
    | {
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      };
  weight?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'job-ads';
        value: number | JobAd;
      } | null)
    | ({
        relationTo: 'traffic-disruptions';
        value: number | TrafficDisruption;
      } | null)
    | ({
        relationTo: 'polls';
        value: number | Poll;
      } | null)
    | ({
        relationTo: 'check-ins';
        value: number | CheckIn;
      } | null)
    | ({
        relationTo: 'neighborhoods';
        value: number | Neighborhood;
      } | null)
    | ({
        relationTo: 'connections';
        value: number | Connection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  name?: T;
  venueName?: T;
  address?: T;
  neighborhood?: T;
  sector?: T;
  latitude?: T;
  longitude?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  place?: T;
  startDate?: T;
  endDate?: T;
  isFree?: T;
  category?: T;
  neighborhoodTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  imageUrl?: T;
  sourceUrl?: T;
  source?: T;
  unverified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons_select".
 */
export interface PersonsSelect<T extends boolean = true> {
  displayName?: T;
  neighborhood?: T;
  commuteType?: T;
  commuteRoute?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  intent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  place?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-ads_select".
 */
export interface JobAdsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  business?: T;
  place?: T;
  category?: T;
  jobType?: T;
  location?: T;
  applyLink?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "traffic-disruptions_select".
 */
export interface TrafficDisruptionsSelect<T extends boolean = true> {
  reason?: T;
  routeType?: T;
  route?: T;
  street?: T;
  sector?: T;
  startDate?: T;
  endDate?: T;
  source?: T;
  sourceUrl?: T;
  unverified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  question?: T;
  description?: T;
  place?: T;
  communityType?: T;
  communityName?: T;
  startsAt?: T;
  endsAt?: T;
  options?:
    | T
    | {
        option?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "check-ins_select".
 */
export interface CheckInsSelect<T extends boolean = true> {
  person?: T;
  event?: T;
  place?: T;
  checkedInAt?: T;
  openToChat?: T;
  optIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighborhoods_select".
 */
export interface NeighborhoodsSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  description?: T;
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect<T extends boolean = true> {
  type?: T;
  sourceType?: T;
  source?: T;
  targetType?: T;
  target?: T;
  weight?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}